### ISSUE TITLE
Proxy cache for fingerprints

### ISSUE THREAD

**Issue by mnmkng** [apify/browser-pool#64]
I'm not sure if it's the best solution. Right now, when I use the default generic Apify proxy URL, it will always give me the same fingerprint, but the IPs will auto-rotate. It also gives the user no control over over the use of the fingerprints. I like the `got-scraping` [`sessionToken`](https://github.com/apify/got-scraping#sessiontoken) solution better and I think we should do it this way, before we make fingerprints default in the SDK.

**Comment by B4nan** [comment]
I guess this one is still valid and should be prioritized given we want to enable fingerprints by default? Or something changed? cc @petrpatek

**Comment by petrpatek** [comment]
Yes, it is. Maybe you guys can do it the same as in got-scraping?

**Comment by szmarczak** [comment]
Here's the cache: https://github.com/apify/browser-pool/blob/308c4ef0a7615b5ffdb4a019bd195774cb78ee59/src/fingerprinting/hooks.ts#L25

Since the fingerprint should be per-page, I think we need to merge `createFingerprintPreLaunchHook` into `createPrePageCreateHook` first.

Then, we should create a WeakMap [here](https://github.com/apify/browser-pool/blob/308c4ef0a7615b5ffdb4a019bd195774cb78ee59/src/fingerprinting/hooks.ts#L6). The logic needs to be replaced with something like this:

```ts
const defaultToken = {}; // WeakMap doesn't accept Symbols yet
...

const token = pageOptions.sessionToken ?? defaultToken;
if (!(weakCache.has(token))) {
    weakCache.set(token, fingerprintGenerator.getFingerprint...);
}

const fingerprint = weakCache.get(token);
```

I don't think there's a better way to pass the `sessionToken` other than via `pageOptions`, however I'm open for other ideas, two heads better than one :) We would need to update the `pageOptions` typings accordingly.

A `Session` needs to be passed to `sessionToken`.
